# Generated by Django 5.2 on 2025-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0002_auto_20250404_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
