# Generated by Django 4.2.14 on 2025-03-28 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("fathername", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHRISTAN", "CHRISTAN"),
                            ("HINDU", "HINDU"),
                            ("CHRISTIAN", "CHRISTIAN"),
                            ("MUSLIM", "MUSLIM"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "admission_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONVENER", "CONVENER"),
                            ("SPOT", "SPOT"),
                            ("MANAGEMENT", "MANAGEMENT"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BC-A", "BC-A"),
                            ("BC-B", "BC-B"),
                            ("BC-C", "BC-C"),
                            ("BC-D", "BC-D"),
                            ("BC-E", "BC-E"),
                            ("OBC", "OBC"),
                            ("SC", "SC"),
                            ("OC", "OC"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("mole", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CSE", "CSE"),
                            ("CSM", "CSM"),
                            ("ECE", "ECE"),
                            ("IT", "IT"),
                            ("CSD", "CSD"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("section", models.CharField(blank=True, max_length=1, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
